version: '3.8'

networks:
  inception:
    name: inception

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx/.
    image: nginx
    ports:
      - "443:443"
    networks:
      - inception
    env_file:
      - .env_general
    volumes:
      - wp-data:/domains
    restart: always

  mariadb:
    container_name: mariadb
    build: 
      context: ./mariadb/.
    image: mariadb
    networks:
      - inception
    env_file:
      - .env_db
    volumes:
      - db-data:/var/lib/mysql
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: ./wordpress/.
    image: wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    env_file:
      - .env_general
      - .env_db
      - .env_wordpress
    volumes:
      - wp-data:/domains
    restart: always

volumes:
  wp-data:
    driver_opts:
      type: none
      device: /home/abeltran/data/volumes/web
      o: bind
  db-data:
    driver_opts:
      type: none
      device: /home/abeltran/data/volumes/db
      o: bind
